apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: whoami-multi-env
  namespace: ${ARGOCD_NS}
spec:
  generators:
    - list:
        elements:
          - env: dev
            ns: whoami-dev
            path: apps/whoami/overlays/dev
            autoSync: "true"
          - env: stage
            ns: whoami-stage
            path: apps/whoami/overlays/stage
            autoSync: "true"
          - env: prod
            ns: whoami-prod
            path: apps/whoami/overlays/prod
            autoSync: "false"

  template:
    metadata:
      name: 'whoami-'
      labels:
        app.kubernetes.io/part-of: whoami
        env: ''
    spec:
      project: whoami-platform
      source:
        repoURL: ${REPO_URL}
        targetRevision: main
      path: ''
      destination:
        server: https://kubernetes.default.svc
        namespace: ''
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
